---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=dist

    - name: Check rebbot
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

